In [41]:
import pandas as pd
import numpy as np 
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.gaussian_process import GaussianProcessRegressor as gpr
from sklearn.gaussian_process.kernels import Matern, ConstantKernel as C
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

In [42]:
PREDICTORS = ["pH", "Cond", "Temp", "OD", "Tds", "Resist", "Salin", "ORP", "IP", "Cor"] # 10 entradas
PREDICTORS = ["pH", "Cond", "Temp", "OD", "Tds", "IP"] 
TARGETS = ["Fe", "Al", "As", "Pb", "Zn", "Hg", "Co", "V", "Ba", "Mn"] # 10 saidas

SCALER = StandardScaler()
OUT_SCALER = StandardScaler()

N_COMPONENTS = 6

In [43]:
Dataset = pd.read_excel("../Dados/Dados.xlsx")

Datasets = []

for n in range(1, 5):
    n_data = Dataset[ Dataset["Pontos"] == f"P{n}" ]
    n_data = n_data.drop(columns=["Campanhas", "Pontos"])
    
    n_data_norm = n_data
        
    Datasets.append(n_data)

In [44]:
def CreatePCAdf(pca):
    # Matriz de transformação do PCA
    W = pca.components_.T   # shape (n_variaveis, n_componentes)

    # Nomes das componentes
    cp_names = [f"CP{i+1}" for i in range(W.shape[1])]

    # Criar DataFrame
    df_pca = pd.DataFrame(
        data=np.round(W, 3),
        index=PREDICTORS,
        columns=cp_names
    )

    return df_pca

In [45]:
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression

def TransformPLS(X_train, X_test, y_train):

    pls = PLSRegression(n_components=N_COMPONENTS)

    # Ajuste supervisionado (usa X e y)
    X_train_pls = pls.fit_transform(X_train, y_train)[0]
    X_test_pls  = pls.transform(X_test)

    # Variância explicada em X (aproximação)
    var_exp = np.var(X_train_pls, axis=0)
    var_ratio = var_exp / np.sum(var_exp)

    print(f"Variância (%): {np.round(var_ratio * 100, 3)}")
    print(f"Total (%): {np.round(np.sum(var_ratio) * 100, 3)}")

    # DataFrame com pesos (loadings)
    df = pd.DataFrame(
        pls.x_weights_,
        columns=[f"PLS{i+1}" for i in range(N_COMPONENTS)]
    )

    return df, pls, X_train_pls, X_test_pls

In [46]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score

def plot_train_test_samples(
    y_train, y_train_pred,
    y_test, y_test_pred,
    title="GPR – Treinamento e Teste"
):

    samples_train = np.arange(len(y_train))
    samples_test = np.arange(len(y_test))

    # Figura
    fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharey=True)

    # -------- Subfigura (a): Treinamento --------
    axes[0].plot(
        samples_train, y_train,
        'o', label="y train (real)", markersize=5
    )
    axes[0].plot(
        samples_train, y_train_pred,
        'x', label="y train (pred)", markersize=5
    )

    axes[0].set_title("(a) Treinamento")
    axes[0].set_xlabel("Amostras")
    axes[0].set_ylabel("Valor")
    axes[0].legend()
    axes[0].grid(True)

    # axes[0].text(
    #     0.02, 0.95,
    #     f"MSE = {mse_train:.4f}\n$R^2$ = {r2_train:.4f}",
    #     transform=axes[0].transAxes,
    #     verticalalignment="top",
    #     bbox=dict(boxstyle="round", alpha=0.85)
    # )

    # -------- Subfigura (b): Teste --------
    axes[1].plot(
        samples_test, y_test,
        'o', label="y test (real)", markersize=5
    )
    axes[1].plot(
        samples_test, y_test_pred,
        'x', label="y test (pred)", markersize=5
    )

    axes[1].set_title("(b) Teste")
    axes[1].set_xlabel("Amostras")
    axes[1].set_ylabel("Valor")
    axes[1].legend()
    axes[1].grid(True)

    # axes[1].text(
    #     0.02, 0.95,
    #     f"MSE = {mse_test:.4f}\n$R^2$ = {r2_test:.4f}",
    #     transform=axes[1].transAxes,
    #     verticalalignment="top",
    #     bbox=dict(boxstyle="round", alpha=0.85)
    # )

    fig.suptitle(title, fontsize=14)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

In [47]:
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score

def ComputeMetrics(y_train, y_train_pred, y_test, y_test_pred):
     return {
        "mse_train": mean_squared_error(y_train, y_train_pred),
        "r2_train":  r2_score(y_train, y_train_pred),
        "mse_test":  mean_squared_error(y_test, y_test_pred),
        "r2_test":   r2_score(y_test, y_test_pred)
    }

In [48]:
GPR_PARAMS = {
    "Fe": {"nu": 0.5,  "ls_min": 1e-6, "ls_max": 1e6, "alpha": 1e-3},
    "Al": {"nu": 0.5,  "ls_min": 1e-6, "ls_max": 1e9, "alpha": 1e-3},
    "As": {"nu": 0.5,  "ls_min": 1e-6, "ls_max": 1e6, "alpha": 1e-3},
    "Pb": {"nu": 0.5,  "ls_min": 1e-6, "ls_max": 1e9, "alpha": 1e-3},
    "Zn": {"nu": 0.5,  "ls_min": 1e-6, "ls_max": 1e9, "alpha": 1e-3},
    "Hg": {"nu": 0.5, "ls_min": 1e-6, "ls_max": 1e6, "alpha": 1e-3},
    "Co": {"nu": 0.5,  "ls_min": 1e-6, "ls_max": 1e10, "alpha": 1e-3},
    "V":  {"nu": 0.25, "ls_min": 1e-6, "ls_max": 1e6, "alpha": 1e-3},
    "Ba": {"nu": 0.5,  "ls_min": 1e-6, "ls_max": 1e6, "alpha": 1e-3},
    "Mn": {"nu": 1.5,  "ls_min": 1e-6, "ls_max": 1e6, "alpha": 1e-3},
}

In [49]:


def GprModel(X_train_pca, X_test_pca, y_train, y_test, target):

    params = GPR_PARAMS[target]

    kernel = C(1.0) * Matern(
        length_scale=np.ones(X_train_pca.shape[1]),
        nu=params["nu"],
        length_scale_bounds=(params["ls_min"], params["ls_max"])
    )

    model = gpr(
        kernel=kernel,
        alpha=params["alpha"],
        normalize_y=True,
        n_restarts_optimizer=20
    )

   # Treinamento
    model.fit(X_train_pca, y_train)

    # Predições
    y_train_pred = model.predict(X_train_pca)
    y_test_pred = model.predict(X_test_pca)

    # Desnormalização
    y_train_denorm = OUT_SCALER.inverse_transform(y_train.reshape(-1, 1)).ravel()
    y_train_pred_denorm = OUT_SCALER.inverse_transform(y_train_pred.reshape(-1, 1)).ravel()

    y_test_denorm = OUT_SCALER.inverse_transform(y_test.reshape(-1, 1)).ravel()
    y_test_pred_denorm = OUT_SCALER.inverse_transform(y_test_pred.reshape(-1, 1)).ravel()
    
    metrics = ComputeMetrics(y_train_denorm, y_train_pred_denorm,  y_test_denorm, y_test_pred_denorm)
    
    return  metrics

    # plot_train_test_samples(
    #     y_train_denorm, y_train_pred_denorm,
    #     y_test_denorm, y_test_pred_denorm,
    #     title="GPR com Kernel Matern (ν = 0.5)"
    # )

In [ ]:
Results = {}

for i, Dataset in enumerate(Datasets):
    print(f"++++++++++++++++++++++ Pontos {i} ++++++++++++++++++++++++++")

    X = Dataset[PREDICTORS].values
    Y = Dataset[TARGETS].values
    
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    X_train_scaled = SCALER.fit_transform(X_train)
    X_test_scaled  = SCALER.transform(X_test)
    
    for j, target in enumerate(TARGETS):
        
        print(f" → {target}")      
        
        y_train = Y_train[:, j]
        y_test  = Y_test[:, j]
        
        y_train = OUT_SCALER.fit_transform(y_train.reshape(-1, 1)).ravel()
        y_test  = OUT_SCALER.transform(y_test.reshape(-1, 1)).ravel()
        
        df, pls, X_train_pls, X_test_pls = TransformPLS(X_train_scaled, X_test_scaled, y_train)
        # display(df)
        
        metrics = GprModel(X_train_pls, X_test_pls, y_train, y_test, target)
        
        Results[target] = metrics
        
    display(pd.DataFrame(Results).T)

++++++++++++++++++++++ Pontos 0 ++++++++++++++++++++++++++
 → Fe
Variância (%): [2.3445e+01 4.1894e+01 1.2567e+01 5.1690e+00 1.6924e+01 2.0000e-03]
Total (%): 100.0
 → Al
Variância (%): [3.3672e+01 3.3418e+01 5.7710e+00 1.0999e+01 1.6139e+01 2.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 1000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → As
Variância (%): [2.0117e+01 4.4939e+01 6.6250e+00 1.6166e+01 1.2150e+01 2.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 1 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 5 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Pb
Variância (%): [4.5553e+01 1.7666e+01 1.1305e+01 7.0530e+00 1.8420e+01 2.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Zn
Variância (%): [4.7920e+01 9.4370e+00 1.0761e+01 1.3566e+01 1.8313e+01 2.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 1000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Hg
Variância (%): [2.2626e+01 3.7374e+01 1.3164e+01 6.9590e+00 1.9875e+01 2.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Co
Variância (%): [2.4005e+01 3.7508e+01 1.5920e+01 1.8696e+01 3.8680e+00 2.0000e-03]
Total (%): 100.0
 → V
Variância (%): [2.1742e+01 1.0492e+01 3.7476e+01 1.2377e+01 1.7910e+01 2.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Ba
Variância (%): [4.2241e+01 2.5306e+01 1.3552e+01 1.1649e+01 7.2500e+00 2.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Mn
Variância (%): [3.4896e+01 3.0269e+01 1.6231e+01 1.7931e+01 6.5600e-01 1.7000e-02]
Total (%): 100.0

       mse_train  r2_train      mse_test    r2_test
Fe  7.531066e-01  0.999996  44875.790749   0.685113
Al  1.698347e-02  0.999998   4964.494135 -11.043160
As  2.223059e-09  0.999999      0.000529  -0.067264
Pb  5.436081e-07  0.999999      0.207897 -20.158437
Zn  2.624087e-03  0.999997    752.135906  -0.466708
Hg  2.380930e-08  0.999999      0.006228 -28.002243
Co  2.021312e-07  0.999997      0.121006  -0.822704
V   2.098950e-07  0.999997      0.027128   0.393284
Ba  2.157396e-04  0.999998     36.413289   0.354680
Mn  1.034231e-02  0.999997   5129.641662  -0.539988

++++++++++++++++++++++ Pontos 1 ++++++++++++++++++++++++++
 → Fe
Variância (%): [1.9364e+01 8.6600e+00 3.1467e+01 2.6885e+01 1.3622e+01 1.0000e-03]
Total (%): 100.0
 → Al
Variância (%): [3.3101e+01 2.6237e+01 1.5680e+01 1.3889e+01 1.1092e+01 1.0000e-03]
Total (%): 100.0
 → As
Variância (%): [2.9862e+01 3.0620e+01 1.1036e+01 1.4864e+01 1.3617e+01 1.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 5 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Pb
Variância (%): [2.6990e+01 3.7236e+01 1.8002e+01 1.6310e+01 1.4550e+00 6.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Zn
Variância (%): [1.7866e+01 2.9782e+01 3.2291e+01 1.6769e+01 3.0000e-03 3.2890e+00]
Total (%): 100.0
 → Hg
Variância (%): [4.3652e+01 1.2463e+01 1.2807e+01 2.0967e+01 1.0108e+01 2.0000e-03]
Total (%): 100.0
 → Co
Variância (%): [2.3330e+01 3.3149e+01 1.2938e+01 1.5274e+01 1.5307e+01 1.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 1 of parameter k2__length_scale is close to the specified upper bound 10000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 10000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → V
Variância (%): [2.0724e+01 3.7044e+01 1.5787e+01 1.4004e+01 1.2440e+01 1.0000e-03]
Total (%): 100.0
 → Ba
Variância (%): [2.9646e+01 3.3326e+01 1.4091e+01 7.0110e+00 1.5924e+01 2.0000e-03]
Total (%): 100.0
 → Mn
Variância (%): [3.0708e+01 2.9312e+01 1.4166e+01 1.2336e+01 1.3478e+01 1.0000e-03]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

       mse_train  r2_train       mse_test   r2_test
Fe  1.109379e+00  0.999993  111129.454175  0.503896
Al  1.447273e-02  0.999998    8580.262974 -1.410260
As  1.297731e-09  0.999999       0.000634  0.028108
Pb  8.354280e-07  0.999998       4.245280 -0.244239
Zn  1.336681e-03  0.999998     665.657985 -0.296812
Hg  8.688867e-09  0.999999       0.001156 -4.227858
Co  2.313156e-07  0.999997       0.111527 -0.473125
V   2.070366e-07  0.999998       0.025903  0.386070
Ba  5.936549e-04  0.999995      87.016750 -0.701449
Mn  9.118487e-02  0.999983   12663.824650 -2.220337

++++++++++++++++++++++ Pontos 2 ++++++++++++++++++++++++++
 → Fe
Variância (%): [20.119 34.398 10.523 17.538 17.421  0.   ]
Total (%): 100.0
 → Al
Variância (%): [32.658 31.677 13.069 20.     2.596  0.   ]
Total (%): 100.0
 → As
Variância (%): [34.974 20.693  9.333 14.927 20.073  0.   ]
Total (%): 100.0
 → Pb
Variância (%): [23.988 30.759 12.766 15.705 16.782  0.   ]
Total (%): 100.0
 → Zn
Variância (%): [36.63  18.21  12.29  16.016 16.854  0.   ]
Total (%): 100.0
 → Hg
Variância (%): [23.762 31.666 12.298 15.804 16.469  0.   ]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Co
Variância (%): [17.941 36.489 11.707 12.509 21.354  0.   ]
Total (%): 100.0
 → V
Variância (%): [19.37  32.688 26.71   9.186 12.046  0.   ]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 1 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Ba
Variância (%): [18.494 31.619 14.636 17.356 17.895  0.   ]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 1 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 2 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Mn
Variância (%): [23.848 29.176 12.003 18.478 16.495  0.   ]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

       mse_train  r2_train       mse_test    r2_test
Fe  5.024732e-01  0.999997  262650.407354   0.245905
Al  3.284556e-02  0.999999   33440.978309 -56.915702
As  4.941682e-09  0.999998       0.001572   0.338013
Pb  6.638725e-07  0.999997       0.107721  -1.803643
Zn  4.471473e-04  0.999999    1133.978880  -0.138608
Hg  3.712493e-07  0.999997       0.001386  -3.830182
Co  2.601687e-07  0.999993       0.044869   0.207246
V   1.432595e-07  0.999998       0.023291   0.551918
Ba  2.447003e-04  0.999999      53.450604  -0.024554
Mn  6.943493e-03  0.999996    2129.723147   0.267900

++++++++++++++++++++++ Pontos 3 ++++++++++++++++++++++++++
 → Fe
Variância (%): [37.239 26.953 15.001  4.336 16.471  0.   ]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(
d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 4 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Al
Variância (%): [31.079 35.406  7.356  9.04  17.119  0.   ]
Total (%): 100.0
 → As
Variância (%): [41.65  28.699  9.336  4.276 16.038  0.   ]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 1 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Pb
Variância (%): [26.385 33.818 10.82   9.86  19.117  0.   ]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Zn
Variância (%): [41.985 21.435 20.455  3.202 12.923  0.   ]
Total (%): 100.0
 → Hg
Variância (%): [22.523 41.45  17.095  2.781 16.152  0.   ]
Total (%): 100.0
 → Co
Variância (%): [19.585 36.005 24.868  3.725 15.816  0.   ]
Total (%): 100.0
 → V
Variância (%): [25.972 41.088  9.235  7.021 16.684  0.   ]
Total (%): 100.0
 → Ba
Variância (%): [45.672 18.491 20.192  2.748 12.896  0.   ]
Total (%): 100.0

d:\Users\sarah\Educ\Ic-2025.2\tf-env\lib\site-packages\sklearn\gaussian_process\kernels.py:450: ConvergenceWarning: The optimal value found for dimension 3 of parameter k2__length_scale is close to the specified upper bound 1000000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(

 → Mn
Variância (%): [30.085 31.2   20.296  2.88  15.539  0.   ]
Total (%): 100.0

       mse_train  r2_train       mse_test    r2_test
Fe  4.980257e-01  0.999997  262707.137923   0.095870
Al  7.261680e-02  0.999998  112705.026670 -56.403258
As  1.725259e-08  0.999997       0.000382   0.800611
Pb  5.799590e-06  0.999994       0.072038  -5.275402
Zn  1.109052e-03  0.999997     481.071811  -0.057589
Hg  6.700892e-09  0.999999       0.007058  -0.007351
Co  1.057155e-07  0.999995       0.019318   0.076688
V   1.547366e-07  0.999998       0.032728   0.138711
Ba  8.162890e-04  0.999996      72.757715  -0.366592
Mn  9.231544e-03  0.999990    1195.084209   0.095073

: